import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdirSync, writeFileSync, rmSync, readFileSync } from "fs";
import { readFile, writeFile } from "fs/promises";
import { join } from "path";
import { MockBackend } from "../helpers/mock-backend";
import { OnePasswordBackend } from "../../src/backends/onepassword";
import { BitwardenBackend } from "../../src/backends/bitwarden";

describe("pull command logic", () => {
  test("backend.list and backend.read retrieves stored values", async () => {
    const backend = new MockBackend();
    backend.seed("OpenAI", "myapp", "dev", "OPENAI_API_KEY", "sk-123");
    backend.seed("Stripe", "myapp", "dev", "STRIPE_KEY", "sk_test_456");

    const refs = await backend.list("myapp", "dev");
    expect(refs).toHaveLength(2);

    for (const ref of refs) {
      const value = await backend.read(ref);
      expect(value).toBeTruthy();
    }
  });

  test("1Password backend buildInlineRef returns op:// URI for .envrc", () => {
    const backend = new OnePasswordBackend();
    const ref = {
      vault: "shipkey",
      provider: "OpenAI",
      project: "myapp",
      env: "prod",
      field: "OPENAI_API_KEY",
    };
    const inlineRef = backend.buildInlineRef(ref);
    expect(inlineRef).toBe("op://shipkey/OpenAI/myapp-prod/OPENAI_API_KEY");
  });

  test("Bitwarden backend buildInlineRef returns null (direct values)", () => {
    const backend = new BitwardenBackend();
    const ref = {
      vault: "shipkey",
      provider: "OpenAI",
      project: "myapp",
      env: "prod",
      field: "OPENAI_API_KEY",
    };
    expect(backend.buildInlineRef(ref)).toBeNull();
  });

  test("MockBackend list handles empty vault gracefully", async () => {
    const backend = new MockBackend();
    const refs = await backend.list("myapp", "dev");
    expect(refs).toHaveLength(0);
  });

  test("envrc line generation differs by backend type", () => {
    const ref = {
      vault: "shipkey",
      provider: "OpenAI",
      project: "myapp",
      env: "prod",
      field: "OPENAI_API_KEY",
    };

    const opBackend = new OnePasswordBackend();
    const opInlineRef = opBackend.buildInlineRef(ref);
    const opLine = `export OPENAI_API_KEY=$(op read "${opInlineRef}")`;
    expect(opLine).toContain("op read");
    expect(opLine).toContain("op://");

    const bwBackend = new BitwardenBackend();
    const bwInlineRef = bwBackend.buildInlineRef(ref);
    expect(bwInlineRef).toBeNull();
    // When null, pull.ts writes direct value: export KEY="value"
  });
});


describe("pull .dev.vars merge behavior", () => {
  const TMP = join(import.meta.dir, "__pull_devvars_fixtures__");

  beforeEach(() => {
    mkdirSync(TMP, { recursive: true });
  });

  afterEach(() => {
    rmSync(TMP, { recursive: true, force: true });
  });

  test(".dev.vars merge updates existing keys in-place", async () => {
    // Simulate existing .dev.vars with some keys
    writeFileSync(
      join(TMP, ".dev.vars"),
      "# Auto-generated by shipkey\nDB_URL=old_db\nAPI_KEY=old_api\n"
    );

    // Simulate the merge logic from pull.ts
    const { readFile, writeFile } = await import("fs/promises");
    const entries = [
      { key: "API_KEY", value: "new_api" },
      { key: "NEW_SECRET", value: "secret123" },
    ];

    const devVarsPath = join(TMP, ".dev.vars");
    let existingContent = "";
    try {
      existingContent = await readFile(devVarsPath, "utf-8");
    } catch {
      // noop
    }

    let lines = existingContent ? existingContent.split("\n") : [];
    const updatedKeys = new Set<string>();

    if (lines.length === 0 || (lines.length === 1 && lines[0] === "")) {
      lines = [
        "# Auto-generated by shipkey — do not edit manually",
        "# Project: test  Environment: dev",
        "",
      ];
    }

    for (let i = 0; i < lines.length; i++) {
      for (const e of entries) {
        if (lines[i].startsWith(`${e.key}=`)) {
          lines[i] = `${e.key}=${e.value}`;
          updatedKeys.add(e.key);
        }
      }
    }

    const newEntries = entries.filter((e) => !updatedKeys.has(e.key));
    for (const e of newEntries) {
      const newLine = `${e.key}=${e.value}`;
      if (lines.length > 0 && lines[lines.length - 1] === "") {
        lines.splice(lines.length - 1, 0, newLine);
      } else {
        lines.push(newLine);
      }
    }

    const devVarsContent =
      lines.join("\n") + (lines[lines.length - 1] !== "" ? "\n" : "");
    await writeFile(devVarsPath, devVarsContent);

    const content = readFileSync(devVarsPath, "utf-8");

    // Comment preserved
    expect(content).toContain("# Auto-generated by shipkey");
    // Existing key NOT overwritten — updated in-place
    expect(content).toContain("API_KEY=new_api");
    expect(content).not.toContain("API_KEY=old_api");
    // Untouched key preserved
    expect(content).toContain("DB_URL=old_db");
    // New key appended
    expect(content).toContain("NEW_SECRET=secret123");

    // Verify ordering: DB_URL still before API_KEY (in-place update)
    const contentLines = content.split("\n").filter((l) => l.includes("=") && !l.startsWith("#"));
    const dbIdx = contentLines.findIndex((l) => l.startsWith("DB_URL="));
    const apiIdx = contentLines.findIndex((l) => l.startsWith("API_KEY="));
    expect(dbIdx).toBeLessThan(apiIdx);
  });

  test(".dev.vars creates file with header when none exists", async () => {
    const { readFile, writeFile } = await import("fs/promises");
    const entries = [{ key: "SECRET", value: "val" }];

    const devVarsPath = join(TMP, ".dev.vars");
    let existingContent = "";
    try {
      existingContent = await readFile(devVarsPath, "utf-8");
    } catch {
      // noop
    }

    let lines = existingContent ? existingContent.split("\n") : [];
    const updatedKeys = new Set<string>();

    if (lines.length === 0 || (lines.length === 1 && lines[0] === "")) {
      lines = [
        "# Auto-generated by shipkey — do not edit manually",
        "# Project: myapp  Environment: dev",
        "",
      ];
    }

    for (let i = 0; i < lines.length; i++) {
      for (const e of entries) {
        if (lines[i].startsWith(`${e.key}=`)) {
          lines[i] = `${e.key}=${e.value}`;
          updatedKeys.add(e.key);
        }
      }
    }

    const newEntries = entries.filter((e) => !updatedKeys.has(e.key));
    for (const e of newEntries) {
      const newLine = `${e.key}=${e.value}`;
      if (lines.length > 0 && lines[lines.length - 1] === "") {
        lines.splice(lines.length - 1, 0, newLine);
      } else {
        lines.push(newLine);
      }
    }

    const devVarsContent =
      lines.join("\n") + (lines[lines.length - 1] !== "" ? "\n" : "");
    await writeFile(devVarsPath, devVarsContent);

    const content = readFileSync(devVarsPath, "utf-8");

    expect(content).toContain("# Auto-generated by shipkey");
    expect(content).toContain("SECRET=val");
  });

  test(".dev.vars merge does not duplicate keys on repeated pulls", async () => {
    const { readFile, writeFile } = await import("fs/promises");
    const devVarsPath = join(TMP, ".dev.vars");

    // First pull
    writeFileSync(devVarsPath, "# Header\nKEY_A=val1\n");

    // Simulate a second pull with same key + new key
    const entries = [
      { key: "KEY_A", value: "val1_updated" },
      { key: "KEY_B", value: "val2" },
    ];

    let existingContent = await readFile(devVarsPath, "utf-8");
    let lines = existingContent.split("\n");
    const updatedKeys = new Set<string>();

    for (let i = 0; i < lines.length; i++) {
      for (const e of entries) {
        if (lines[i].startsWith(`${e.key}=`)) {
          lines[i] = `${e.key}=${e.value}`;
          updatedKeys.add(e.key);
        }
      }
    }

    const newEntries = entries.filter((e) => !updatedKeys.has(e.key));
    for (const e of newEntries) {
      const newLine = `${e.key}=${e.value}`;
      if (lines.length > 0 && lines[lines.length - 1] === "") {
        lines.splice(lines.length - 1, 0, newLine);
      } else {
        lines.push(newLine);
      }
    }

    const devVarsContent =
      lines.join("\n") + (lines[lines.length - 1] !== "" ? "\n" : "");
    await writeFile(devVarsPath, devVarsContent);

    const content = readFileSync(devVarsPath, "utf-8");

    // KEY_A should appear exactly once (updated, not duplicated)
    const keyAMatches = content.split("\n").filter((l) => l.startsWith("KEY_A="));
    expect(keyAMatches).toHaveLength(1);
    expect(keyAMatches[0]).toBe("KEY_A=val1_updated");

    // KEY_B appended
    expect(content).toContain("KEY_B=val2");
  });
});

// ---- Helper: replicate the in-place .env merge logic from pull.ts ----
async function mergeEnvFile(
  envPath: string,
  entries: { key: string; value: string }[]
): Promise<{ updatedCount: number; newCount: number }> {
  const pulledKeys = new Map(entries.map((e) => [e.key, e.value]));
  const MARKER = "# generated by shipkey";

  let updatedCount = 0;
  let newCount = 0;
  let outputLines: string[];

  try {
    const existing = await readFile(envPath, "utf-8");
    const lines = existing.split("\n");
    const seen = new Set<string>();

    outputLines = lines.map((line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) return line;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) return line;
      const key = trimmed.slice(0, eqIdx);
      if (pulledKeys.has(key)) {
        seen.add(key);
        updatedCount++;
        return `${key}=${pulledKeys.get(key)} ${MARKER}`;
      }
      return line.replace(/ # generated by shipkey$/, "");
    });

    const newKeys = entries.filter((e) => !seen.has(e.key));
    if (newKeys.length > 0) {
      if (outputLines.length > 0 && outputLines[outputLines.length - 1]?.trim() !== "") {
        outputLines.push("");
      }
      for (const e of newKeys) {
        outputLines.push(`${e.key}=${e.value} ${MARKER}`);
        newCount++;
      }
    }
  } catch {
    outputLines = entries.map((e) => `${e.key}=${e.value} ${MARKER}`);
    outputLines.push("");
    updatedCount = entries.length;
  }

  await writeFile(envPath, outputLines.join("\n"));
  return { updatedCount, newCount };
}

describe("pull .env in-place merge with shipkey marker", () => {
  const TMP = join(import.meta.dir, "__pull_env_inplace__");

  beforeEach(() => {
    mkdirSync(TMP, { recursive: true });
  });

  afterEach(() => {
    rmSync(TMP, { recursive: true, force: true });
  });

  test("preserves comments, blank lines, and key ordering", async () => {
    const envPath = join(TMP, ".env");
    writeFileSync(
      envPath,
      [
        "# Database config",
        "DATABASE_URL=postgresql://localhost/mydb",
        "PORT=3000",
        "",
        "# Third-party APIs",
        "STRIPE_KEY=sk_test_old",
      ].join("\n")
    );

    await mergeEnvFile(envPath, [
      { key: "DATABASE_URL", value: "postgresql://prod/mydb" },
      { key: "STRIPE_KEY", value: "sk_live_new" },
    ]);

    const lines = readFileSync(envPath, "utf-8").split("\n");
    expect(lines[0]).toBe("# Database config");
    expect(lines[1]).toBe("DATABASE_URL=postgresql://prod/mydb # generated by shipkey");
    expect(lines[2]).toBe("PORT=3000");
    expect(lines[3]).toBe("");
    expect(lines[4]).toBe("# Third-party APIs");
    expect(lines[5]).toBe("STRIPE_KEY=sk_live_new # generated by shipkey");
  });

  test("local-only keys are preserved untouched", async () => {
    const envPath = join(TMP, ".env");
    writeFileSync(envPath, "API_KEY=from_vault\nMY_LOCAL=debug_val\n");

    await mergeEnvFile(envPath, [{ key: "API_KEY", value: "new_val" }]);

    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain("MY_LOCAL=debug_val");
    expect(content).not.toContain("MY_LOCAL=debug_val # generated by shipkey");
    expect(content).toContain("API_KEY=new_val # generated by shipkey");
  });

  test("strips old marker from keys no longer in password manager", async () => {
    const envPath = join(TMP, ".env");
    writeFileSync(envPath, "OLD_KEY=old_val # generated by shipkey\nLOCAL=x\n");

    // Pull without OLD_KEY
    await mergeEnvFile(envPath, []);

    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain("OLD_KEY=old_val");
    expect(content).not.toContain("# generated by shipkey");
  });

  test("appends new keys from password manager not in local file", async () => {
    const envPath = join(TMP, ".env");
    writeFileSync(envPath, "EXISTING=val\n");

    const result = await mergeEnvFile(envPath, [
      { key: "EXISTING", value: "updated" },
      { key: "BRAND_NEW", value: "fresh" },
    ]);

    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain("EXISTING=updated # generated by shipkey");
    expect(content).toContain("BRAND_NEW=fresh # generated by shipkey");
    expect(result.updatedCount).toBe(1);
    expect(result.newCount).toBe(1);
  });

  test("creates .env from scratch when file does not exist", async () => {
    const envPath = join(TMP, ".env");

    await mergeEnvFile(envPath, [
      { key: "KEY_A", value: "val_a" },
      { key: "KEY_B", value: "val_b" },
    ]);

    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain("KEY_A=val_a # generated by shipkey");
    expect(content).toContain("KEY_B=val_b # generated by shipkey");
  });

  test("repeated pulls do not duplicate keys", async () => {
    const envPath = join(TMP, ".env");
    writeFileSync(envPath, "API_KEY=v1\nDB_URL=db1\n");

    const entries = [
      { key: "API_KEY", value: "v2" },
      { key: "DB_URL", value: "db2" },
    ];

    // First pull
    await mergeEnvFile(envPath, entries);
    // Second pull
    await mergeEnvFile(envPath, entries);

    const lines = readFileSync(envPath, "utf-8").split("\n");
    const apiLines = lines.filter((l) => l.startsWith("API_KEY="));
    const dbLines = lines.filter((l) => l.startsWith("DB_URL="));
    expect(apiLines).toHaveLength(1);
    expect(dbLines).toHaveLength(1);
  });
});
