import { Command } from "commander";
import { getBackend } from "../backends";
import { loadConfig } from "../config";
import { walkDirsWithShipkey } from "../scanner";
import { readFile, writeFile } from "fs/promises";
import { resolve, join, relative } from "path";

export const pullCommand = new Command("pull")
  .description("Pull keys from your password manager and generate env files")
  .option("-e, --env <env>", "environment (dev/prod)", "prod")
  .option("--vault <vault>", "Vault or folder name", "shipkey")
  .option("--envrc", "generate .envrc (direnv)")
  .option("--dev-vars", "generate .dev.vars for Cloudflare Workers")
  .argument("[dir]", "project directory", ".")
  .action(async (dir: string, opts) => {
    const projectRoot = resolve(dir);
    const env = opts.env;
    const vault = opts.vault;

    const shipkeyDirs = await walkDirsWithShipkey(projectRoot);

    if (shipkeyDirs.length === 0) {
      console.error(
        "  No shipkey.json found. Run `shipkey scan` first."
      );
      process.exit(1);
    }

    for (const d of shipkeyDirs) {
      const relDir = relative(projectRoot, d) || ".";
      console.log(`\n  [${relDir}]`);

      let config;
      try {
        config = await loadConfig(d);
      } catch {
        console.error(`  ✗ Could not read shipkey.json in ${relDir}`);
        continue;
      }

      const backend = getBackend(config.backend);
      if (!(await backend.isAvailable())) {
        console.error(
          `  ✗ ${backend.name} CLI not available. Run 'shipkey setup' for installation instructions.`
        );
        continue;
      }

      console.log(`  Pulling keys for ${config.project}.${env}...`);

      const refs = await backend.list(config.project, env);

      if (refs.length === 0) {
        console.log(`  No keys found for ${config.project}.${env} in vault ${vault}.`);
        continue;
      }

      const entries: { key: string; value: string; ref: typeof refs[0] }[] = [];
      for (const ref of refs) {
        try {
          const value = await backend.read(ref);
          entries.push({ key: ref.field, value, ref });
          console.log(`  ✓ Restored ${ref.field}`);
        } catch (err) {
          console.error(
            `  ✗ ${ref.provider}/${ref.field} — ${err instanceof Error ? err.message : err}`
          );
        }
      }

      if (entries.length === 0) continue;

      // Generate .env (merge: update pulled keys, preserve local-only keys)
      const envPath = join(d, ".env");
      const pulledKeys = new Map(entries.map((e) => [e.key, e.value]));

      // Read existing .env and preserve local-only keys
      let localOnlyLines: string[] = [];
      try {
        const existing = await readFile(envPath, "utf-8");
        for (const line of existing.split("\n")) {
          const trimmed = line.trim();
          if (!trimmed || trimmed.startsWith("#")) continue;
          const eqIdx = trimmed.indexOf("=");
          if (eqIdx === -1) continue;
          const key = trimmed.slice(0, eqIdx);
          if (!pulledKeys.has(key)) {
            localOnlyLines.push(line);
          }
        }
      } catch {
        // .env doesn't exist yet
      }

      const envLines = [
        `# Auto-generated by shipkey — do not edit manually`,
        `# Project: ${config.project}  Environment: ${env}`,
        "",
        ...entries.map((e) => `${e.key}=${e.value}`),
      ];

      if (localOnlyLines.length > 0) {
        envLines.push("", "# Local keys (not in password manager)");
        envLines.push(...localOnlyLines);
      }

      envLines.push("");

      await writeFile(envPath, envLines.join("\n"));
      console.log(`  ✓ Generated .env (${entries.length} pulled${localOnlyLines.length > 0 ? `, ${localOnlyLines.length} local preserved` : ""})`);

      if (opts.envrc) {
        const envrcContent = [
          `# Auto-generated by shipkey — do not edit manually`,
          `# Project: ${config.project}  Environment: ${env}`,
          "",
          ...entries.map((e) => {
            const inlineRef = backend.buildInlineRef?.(e.ref);
            if (inlineRef) {
              return `export ${e.key}=$(op read "${inlineRef}")`;
            }
            return `export ${e.key}="${e.value}"`;
          }),
          "",
        ].join("\n");

        await writeFile(join(d, ".envrc"), envrcContent);
        console.log(`  ✓ Generated .envrc`);
      }

      if (opts.devVars) {
        // Only include keys listed in cloudflare targets, fall back to all keys
        const cfKeys = new Set<string>();
        const cfTargets = config?.targets?.cloudflare;
        if (cfTargets) {
          for (const keys of Object.values(cfTargets)) {
            if (Array.isArray(keys)) {
              for (const k of keys) cfKeys.add(k);
            }
          }
        }

        const devVarsEntries = cfKeys.size > 0
          ? entries.filter((e) => cfKeys.has(e.key))
          : entries;

        if (devVarsEntries.length > 0) {
          const devVarsContent = [
            `# Auto-generated by shipkey — do not edit manually`,
            `# Project: ${config.project}  Environment: ${env}`,
            "",
            ...devVarsEntries.map((e) => `${e.key}=${e.value}`),
            "",
          ].join("\n");

          await writeFile(join(d, ".dev.vars"), devVarsContent);
          console.log(`  ✓ Generated .dev.vars (${devVarsEntries.length} keys)`);
        }
      }

      console.log(`  Restored ${entries.length} keys for ${config.project}.${env}`);
    }
  });
