import { Command } from "commander";
import { getBackend } from "../backends";
import { loadConfig } from "../config";
import { readFile, writeFile } from "fs/promises";
import { resolve, join } from "path";
import { resolveProjectDir } from "./project-scope";
import type { SecretBackend, SecretEntry, SecretRef } from "../backends/types";

const MARKER = "# generated by shipkey";

interface PullLoadFailure {
  ref: SecretRef;
  error: string;
}

interface PullLoadResult {
  entries: SecretEntry[];
  failures: PullLoadFailure[];
}

interface EnvMergePlan {
  lines: string[];
  added: string[];
  updated: string[];
  removed: string[];
}

interface DefaultsPlan {
  lines: string[];
  added: string[];
}

export async function writeIfNotDryRun(
  path: string,
  content: string,
  dryRun: boolean
): Promise<boolean> {
  if (dryRun) return false;
  await writeFile(path, content);
  return true;
}

export async function resolveRemoteEntries(
  backend: SecretBackend,
  project: string,
  env: string,
  vault: string
): Promise<PullLoadResult> {
  if (backend.listEntries) {
    return {
      entries: await backend.listEntries(project, env, vault),
      failures: [],
    };
  }

  const refs = await backend.list(project, env, vault);
  const settled = await Promise.allSettled(
    refs.map(async (ref) => ({
      ref,
      value: await backend.read(ref),
    }))
  );

  const entries: SecretEntry[] = [];
  const failures: PullLoadFailure[] = [];

  for (const [index, result] of settled.entries()) {
    if (result.status === "fulfilled") {
      entries.push(result.value);
      continue;
    }

    const reason = result.reason instanceof Error
      ? result.reason.message
      : String(result.reason);
    failures.push({
      ref: refs[index],
      error: reason,
    });
  }

  return { entries, failures };
}

export function planEnvMerge(
  existingContent: string | null,
  entries: SecretEntry[]
): EnvMergePlan {
  const pulledKeys = new Map(entries.map((entry) => [entry.ref.field, entry.value]));
  const added: string[] = [];
  const updated: string[] = [];
  const removed: string[] = [];

  if (existingContent == null) {
    return {
      lines: [
        ...entries.map((entry) => `${entry.ref.field}=${entry.value} ${MARKER}`),
        "",
      ],
      added: entries.map((entry) => entry.ref.field),
      updated,
      removed,
    };
  }

  const lines = existingContent.split("\n");
  const seen = new Set<string>();
  const outputLines = lines.flatMap((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return [line];
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) return [line];
    const key = trimmed.slice(0, eqIdx);

    if (pulledKeys.has(key)) {
      seen.add(key);
      const nextLine = `${key}=${pulledKeys.get(key)} ${MARKER}`;
      if (line !== nextLine) {
        updated.push(key);
      }
      return [nextLine];
    }

    if (line.endsWith(` ${MARKER}`)) {
      removed.push(key);
      return [];
    }

    return [line];
  });

  let appendedBlockStarted = false;
  for (const entry of entries) {
    const key = entry.ref.field;
    if (seen.has(key)) continue;
    if (!appendedBlockStarted && outputLines.length > 0 && outputLines[outputLines.length - 1]?.trim() !== "") {
      outputLines.push("");
    }
    outputLines.push(`${key}=${entry.value} ${MARKER}`);
    appendedBlockStarted = true;
    added.push(key);
    seen.add(key);
  }

  return { lines: outputLines, added, updated, removed };
}

export function planDefaultsFill(
  lines: string[],
  defaults: Record<string, string> | undefined
): DefaultsPlan {
  if (!defaults || Object.keys(defaults).length === 0) {
    return { lines, added: [] };
  }

  const nextLines = [...lines];
  const existingKeys = new Set<string>();
  for (const line of nextLines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx !== -1) existingKeys.add(trimmed.slice(0, eqIdx));
  }

  const added: string[] = [];
  let appendedBlockStarted = false;
  for (const [key, value] of Object.entries(defaults)) {
    if (existingKeys.has(key)) continue;
    if (!appendedBlockStarted && nextLines.length > 0 && nextLines[nextLines.length - 1]?.trim() !== "") {
      nextLines.push("");
    }
    nextLines.push(`${key}=${value}`);
    appendedBlockStarted = true;
    added.push(key);
    existingKeys.add(key);
  }

  return { lines: nextLines, added };
}

export const pullCommand = new Command("pull")
  .description("Pull keys for the current directory and generate env files")
  .option("-e, --env <env>", "environment (overrides shipkey.json)")
  .option("--vault <vault>", "Vault or folder name", "shipkey")
  .option("--dry-run", "show pull diff without writing local files")
  .option("--envrc", "generate .envrc (direnv)")
  .option("--dev-vars", "generate .dev.vars for Cloudflare Workers")
  .argument("[dir]", "project directory", ".")
  .action(async (dir: string, opts) => {
    const projectRoot = resolve(dir);
    const projectDir = await resolveProjectDir(projectRoot);
    if (!projectDir) {
      console.error(
        "  No shipkey.json found. Run `shipkey scan` first."
      );
      process.exit(1);
    }

    const d = projectDir;
    const isDryRun = Boolean(opts.dryRun);
    console.log(`\n  [.]`);

    let config;
    try {
      config = await loadConfig(d);
    } catch {
      console.error("  ✗ Could not read shipkey.json in .");
      process.exit(1);
    }

    const backend = getBackend(config.backend);
    const env = opts.env ?? config.env ?? "dev";
    const vault = opts.vault ?? config.vault ?? "shipkey";
    if (!(await backend.isAvailable())) {
      console.error(
        `  ✗ ${backend.name} CLI not available. Run 'shipkey setup' for installation instructions.`
      );
      process.exit(1);
    }

    console.log(`  Pulling keys for ${config.project}.${env}...`);

    const remote = await resolveRemoteEntries(backend, config.project, env, vault);
    for (const failure of remote.failures) {
      console.error(`  ✗ ${failure.ref.provider}/${failure.ref.field} — ${failure.error}`);
    }

    if (remote.entries.length === 0) {
      console.log(`  No keys found for ${config.project}.${env} in vault ${vault}.`);
      return;
    }

    const envPath = join(d, ".env");
    let existingEnv: string | null = null;
    try {
      existingEnv = await readFile(envPath, "utf-8");
    } catch {
      existingEnv = null;
    }

    const envPlan = planEnvMerge(existingEnv, remote.entries);
    const defaultsPlan = planDefaultsFill(envPlan.lines, config.defaults);

    if (envPlan.added.length > 0) {
      console.log(`  Added secrets (${envPlan.added.length}):`);
      for (const key of envPlan.added) {
        console.log(`    + ${key}`);
      }
    }

    if (envPlan.updated.length > 0) {
      console.log(`  Updated secrets (${envPlan.updated.length}):`);
      for (const key of envPlan.updated) {
        console.log(`    ~ ${key}`);
      }
    }

    if (envPlan.removed.length > 0) {
      console.log(`  Removed secrets (${envPlan.removed.length}):`);
      for (const key of envPlan.removed) {
        console.log(`    - ${key}`);
      }
    }

    if (defaultsPlan.added.length > 0) {
      console.log(`  Added defaults (${defaultsPlan.added.length}):`);
      for (const key of defaultsPlan.added) {
        console.log(`    + ${key}`);
      }
    }

    const hasEnvChanges =
      envPlan.added.length > 0 ||
      envPlan.updated.length > 0 ||
      envPlan.removed.length > 0 ||
      defaultsPlan.added.length > 0;

    if (!hasEnvChanges) {
      console.log("  No .env changes detected.");
    } else {
      await writeIfNotDryRun(envPath, defaultsPlan.lines.join("\n"), isDryRun);
    }

    const parts: string[] = [];
    if (envPlan.updated.length > 0) parts.push(`${envPlan.updated.length} updated`);
    if (envPlan.added.length > 0) parts.push(`${envPlan.added.length} new`);
    if (envPlan.removed.length > 0) parts.push(`${envPlan.removed.length} removed`);
    if (defaultsPlan.added.length > 0) parts.push(`${defaultsPlan.added.length} defaults`);
    if (parts.length === 0) parts.push("unchanged");
    console.log(`  ✓ .env (${parts.join(", ")})`);

    if (opts.envrc) {
      const envrcContent = [
        `# Auto-generated by shipkey — do not edit manually`,
        `# Project: ${config.project}  Environment: ${env}`,
        "",
        ...remote.entries.map((entry) => {
          const inlineRef = backend.buildInlineRef?.(entry.ref);
          if (inlineRef) {
            return `export ${entry.ref.field}=$(op read "${inlineRef}")`;
          }
          return `export ${entry.ref.field}="${entry.value}"`;
        }),
        "",
      ].join("\n");

      await writeIfNotDryRun(join(d, ".envrc"), envrcContent, isDryRun);
      console.log(`  ✓ ${isDryRun ? "Would generate" : "Generated"} .envrc`);
    }

    if (opts.devVars) {
      const cfKeys = new Set<string>();
      const cfTargets = config?.targets?.cloudflare;
      if (cfTargets) {
        for (const keys of Object.values(cfTargets)) {
          if (Array.isArray(keys)) {
            for (const k of keys) cfKeys.add(k);
          }
        }
      }

      const devVarsEntries = cfKeys.size > 0
        ? remote.entries.filter((entry) => cfKeys.has(entry.ref.field))
        : remote.entries;

      if (devVarsEntries.length > 0) {
        const devVarsContent = [
          `# Auto-generated by shipkey — do not edit manually`,
          `# Project: ${config.project}  Environment: ${env}`,
          "",
          ...devVarsEntries.map((entry) => `${entry.ref.field}=${entry.value}`),
          "",
        ].join("\n");

        await writeIfNotDryRun(join(d, ".dev.vars"), devVarsContent, isDryRun);
        console.log(
          `  ✓ ${isDryRun ? "Would generate" : "Generated"} .dev.vars (${devVarsEntries.length} keys)`
        );
      }
    }

    if (isDryRun) {
      console.log("  (dry-run: no local files were written)");
    }
    console.log(`  Restored ${remote.entries.length} keys for ${config.project}.${env}`);
  });
